syntax = "proto3";

package likewhat;

option go_package = "github.com/Parnishkaspb/LikeWhat/pkg/like_what;likewhat";

import "google/protobuf/timestamp.proto";

// TobaccoService manages a collection of product tobaccos.
service TobaccoService {
  rpc CreateTobacco(CreateTobaccoRequest) returns (Tobacco);
  rpc GetTobacco(GetTobaccoRequest) returns (Tobacco);
  rpc ListTobaccos(ListTobaccosRequest) returns (ListTobaccosResponse);
}

message Tobacco {
  string id = 1;
  string taste = 2;
  string proto = 3;
  Manufacture manufacture = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp updated_at = 6;
  google.protobuf.Timestamp deleted_at = 7;
}

message CreateTobaccoRequest {
  string taste = 1;
  string photo = 2;
  string manufacture_id = 3;
}

message Manufacture {
  string id = 1;
  string name = 2;
}

message GetTobaccoRequest {
  string id = 1;
}

message ListTobaccosRequest {
  string taste = 1;
  repeated string manufacture_id = 2;
}

message ListTobaccosResponse {
  repeated Tobacco tobaccos = 1;
}
