// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/like_what/like_what.proto

package likewhat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tobacco struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Taste         string                 `protobuf:"bytes,2,opt,name=taste,proto3" json:"taste,omitempty"`
	Proto         string                 `protobuf:"bytes,3,opt,name=proto,proto3" json:"proto,omitempty"`
	Manufacture   *Manufacture           `protobuf:"bytes,4,opt,name=manufacture,proto3" json:"manufacture,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tobacco) Reset() {
	*x = Tobacco{}
	mi := &file_api_like_what_like_what_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tobacco) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tobacco) ProtoMessage() {}

func (x *Tobacco) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tobacco.ProtoReflect.Descriptor instead.
func (*Tobacco) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{0}
}

func (x *Tobacco) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tobacco) GetTaste() string {
	if x != nil {
		return x.Taste
	}
	return ""
}

func (x *Tobacco) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *Tobacco) GetManufacture() *Manufacture {
	if x != nil {
		return x.Manufacture
	}
	return nil
}

func (x *Tobacco) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tobacco) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Tobacco) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreateTobaccoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taste         string                 `protobuf:"bytes,1,opt,name=taste,proto3" json:"taste,omitempty"`
	Photo         string                 `protobuf:"bytes,2,opt,name=photo,proto3" json:"photo,omitempty"`
	ManufactureId string                 `protobuf:"bytes,3,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTobaccoRequest) Reset() {
	*x = CreateTobaccoRequest{}
	mi := &file_api_like_what_like_what_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTobaccoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTobaccoRequest) ProtoMessage() {}

func (x *CreateTobaccoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTobaccoRequest.ProtoReflect.Descriptor instead.
func (*CreateTobaccoRequest) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTobaccoRequest) GetTaste() string {
	if x != nil {
		return x.Taste
	}
	return ""
}

func (x *CreateTobaccoRequest) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *CreateTobaccoRequest) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

type Manufacture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacture) Reset() {
	*x = Manufacture{}
	mi := &file_api_like_what_like_what_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacture) ProtoMessage() {}

func (x *Manufacture) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacture.ProtoReflect.Descriptor instead.
func (*Manufacture) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{2}
}

func (x *Manufacture) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manufacture) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTobaccoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTobaccoRequest) Reset() {
	*x = GetTobaccoRequest{}
	mi := &file_api_like_what_like_what_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTobaccoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTobaccoRequest) ProtoMessage() {}

func (x *GetTobaccoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTobaccoRequest.ProtoReflect.Descriptor instead.
func (*GetTobaccoRequest) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{3}
}

func (x *GetTobaccoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTobaccosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taste         string                 `protobuf:"bytes,1,opt,name=taste,proto3" json:"taste,omitempty"`
	ManufactureId []string               `protobuf:"bytes,2,rep,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTobaccosRequest) Reset() {
	*x = ListTobaccosRequest{}
	mi := &file_api_like_what_like_what_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTobaccosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTobaccosRequest) ProtoMessage() {}

func (x *ListTobaccosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTobaccosRequest.ProtoReflect.Descriptor instead.
func (*ListTobaccosRequest) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{4}
}

func (x *ListTobaccosRequest) GetTaste() string {
	if x != nil {
		return x.Taste
	}
	return ""
}

func (x *ListTobaccosRequest) GetManufactureId() []string {
	if x != nil {
		return x.ManufactureId
	}
	return nil
}

type ListTobaccosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tobaccos      []*Tobacco             `protobuf:"bytes,1,rep,name=tobaccos,proto3" json:"tobaccos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTobaccosResponse) Reset() {
	*x = ListTobaccosResponse{}
	mi := &file_api_like_what_like_what_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTobaccosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTobaccosResponse) ProtoMessage() {}

func (x *ListTobaccosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTobaccosResponse.ProtoReflect.Descriptor instead.
func (*ListTobaccosResponse) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{5}
}

func (x *ListTobaccosResponse) GetTobaccos() []*Tobacco {
	if x != nil {
		return x.Tobaccos
	}
	return nil
}

var File_api_like_what_like_what_proto protoreflect.FileDescriptor

const file_api_like_what_like_what_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/like_what/like_what.proto\x12\blikewhat\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\aTobacco\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05taste\x18\x02 \x01(\tR\x05taste\x12\x14\n" +
	"\x05proto\x18\x03 \x01(\tR\x05proto\x127\n" +
	"\vmanufacture\x18\x04 \x01(\v2\x15.likewhat.ManufactureR\vmanufacture\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"i\n" +
	"\x14CreateTobaccoRequest\x12\x14\n" +
	"\x05taste\x18\x01 \x01(\tR\x05taste\x12\x14\n" +
	"\x05photo\x18\x02 \x01(\tR\x05photo\x12%\n" +
	"\x0emanufacture_id\x18\x03 \x01(\tR\rmanufactureId\"1\n" +
	"\vManufacture\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"#\n" +
	"\x11GetTobaccoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x13ListTobaccosRequest\x12\x14\n" +
	"\x05taste\x18\x01 \x01(\tR\x05taste\x12%\n" +
	"\x0emanufacture_id\x18\x02 \x03(\tR\rmanufactureId\"E\n" +
	"\x14ListTobaccosResponse\x12-\n" +
	"\btobaccos\x18\x01 \x03(\v2\x11.likewhat.TobaccoR\btobaccos2\xe1\x01\n" +
	"\x0eTobaccoService\x12B\n" +
	"\rCreateTobacco\x12\x1e.likewhat.CreateTobaccoRequest\x1a\x11.likewhat.Tobacco\x12<\n" +
	"\n" +
	"GetTobacco\x12\x1b.likewhat.GetTobaccoRequest\x1a\x11.likewhat.Tobacco\x12M\n" +
	"\fListTobaccos\x12\x1d.likewhat.ListTobaccosRequest\x1a\x1e.likewhat.ListTobaccosResponseB9Z7github.com/Parnishkaspb/LikeWhat/pkg/like_what;likewhatb\x06proto3"

var (
	file_api_like_what_like_what_proto_rawDescOnce sync.Once
	file_api_like_what_like_what_proto_rawDescData []byte
)

func file_api_like_what_like_what_proto_rawDescGZIP() []byte {
	file_api_like_what_like_what_proto_rawDescOnce.Do(func() {
		file_api_like_what_like_what_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_like_what_like_what_proto_rawDesc), len(file_api_like_what_like_what_proto_rawDesc)))
	})
	return file_api_like_what_like_what_proto_rawDescData
}

var file_api_like_what_like_what_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_like_what_like_what_proto_goTypes = []any{
	(*Tobacco)(nil),               // 0: likewhat.Tobacco
	(*CreateTobaccoRequest)(nil),  // 1: likewhat.CreateTobaccoRequest
	(*Manufacture)(nil),           // 2: likewhat.Manufacture
	(*GetTobaccoRequest)(nil),     // 3: likewhat.GetTobaccoRequest
	(*ListTobaccosRequest)(nil),   // 4: likewhat.ListTobaccosRequest
	(*ListTobaccosResponse)(nil),  // 5: likewhat.ListTobaccosResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_like_what_like_what_proto_depIdxs = []int32{
	2, // 0: likewhat.Tobacco.manufacture:type_name -> likewhat.Manufacture
	6, // 1: likewhat.Tobacco.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: likewhat.Tobacco.updated_at:type_name -> google.protobuf.Timestamp
	6, // 3: likewhat.Tobacco.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 4: likewhat.ListTobaccosResponse.tobaccos:type_name -> likewhat.Tobacco
	1, // 5: likewhat.TobaccoService.CreateTobacco:input_type -> likewhat.CreateTobaccoRequest
	3, // 6: likewhat.TobaccoService.GetTobacco:input_type -> likewhat.GetTobaccoRequest
	4, // 7: likewhat.TobaccoService.ListTobaccos:input_type -> likewhat.ListTobaccosRequest
	0, // 8: likewhat.TobaccoService.CreateTobacco:output_type -> likewhat.Tobacco
	0, // 9: likewhat.TobaccoService.GetTobacco:output_type -> likewhat.Tobacco
	5, // 10: likewhat.TobaccoService.ListTobaccos:output_type -> likewhat.ListTobaccosResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_like_what_like_what_proto_init() }
func file_api_like_what_like_what_proto_init() {
	if File_api_like_what_like_what_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_like_what_like_what_proto_rawDesc), len(file_api_like_what_like_what_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_like_what_like_what_proto_goTypes,
		DependencyIndexes: file_api_like_what_like_what_proto_depIdxs,
		MessageInfos:      file_api_like_what_like_what_proto_msgTypes,
	}.Build()
	File_api_like_what_like_what_proto = out.File
	file_api_like_what_like_what_proto_goTypes = nil
	file_api_like_what_like_what_proto_depIdxs = nil
}
