// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/like_what/like_what.proto

package likewhat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TobaccoService_CreateTobacco_FullMethodName = "/likewhat.TobaccoService/CreateTobacco"
	TobaccoService_GetTobacco_FullMethodName    = "/likewhat.TobaccoService/GetTobacco"
	TobaccoService_ListTobaccos_FullMethodName  = "/likewhat.TobaccoService/ListTobaccos"
)

// TobaccoServiceClient is the client API for TobaccoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TobaccoService manages a collection of product tobaccos.
type TobaccoServiceClient interface {
	CreateTobacco(ctx context.Context, in *CreateTobaccoRequest, opts ...grpc.CallOption) (*Tobacco, error)
	GetTobacco(ctx context.Context, in *GetTobaccoRequest, opts ...grpc.CallOption) (*Tobacco, error)
	ListTobaccos(ctx context.Context, in *ListTobaccosRequest, opts ...grpc.CallOption) (*ListTobaccosResponse, error)
}

type tobaccoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTobaccoServiceClient(cc grpc.ClientConnInterface) TobaccoServiceClient {
	return &tobaccoServiceClient{cc}
}

func (c *tobaccoServiceClient) CreateTobacco(ctx context.Context, in *CreateTobaccoRequest, opts ...grpc.CallOption) (*Tobacco, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tobacco)
	err := c.cc.Invoke(ctx, TobaccoService_CreateTobacco_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tobaccoServiceClient) GetTobacco(ctx context.Context, in *GetTobaccoRequest, opts ...grpc.CallOption) (*Tobacco, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tobacco)
	err := c.cc.Invoke(ctx, TobaccoService_GetTobacco_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tobaccoServiceClient) ListTobaccos(ctx context.Context, in *ListTobaccosRequest, opts ...grpc.CallOption) (*ListTobaccosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTobaccosResponse)
	err := c.cc.Invoke(ctx, TobaccoService_ListTobaccos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TobaccoServiceServer is the server API for TobaccoService service.
// All implementations must embed UnimplementedTobaccoServiceServer
// for forward compatibility.
//
// TobaccoService manages a collection of product tobaccos.
type TobaccoServiceServer interface {
	CreateTobacco(context.Context, *CreateTobaccoRequest) (*Tobacco, error)
	GetTobacco(context.Context, *GetTobaccoRequest) (*Tobacco, error)
	ListTobaccos(context.Context, *ListTobaccosRequest) (*ListTobaccosResponse, error)
	mustEmbedUnimplementedTobaccoServiceServer()
}

// UnimplementedTobaccoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTobaccoServiceServer struct{}

func (UnimplementedTobaccoServiceServer) CreateTobacco(context.Context, *CreateTobaccoRequest) (*Tobacco, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTobacco not implemented")
}
func (UnimplementedTobaccoServiceServer) GetTobacco(context.Context, *GetTobaccoRequest) (*Tobacco, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTobacco not implemented")
}
func (UnimplementedTobaccoServiceServer) ListTobaccos(context.Context, *ListTobaccosRequest) (*ListTobaccosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTobaccos not implemented")
}
func (UnimplementedTobaccoServiceServer) mustEmbedUnimplementedTobaccoServiceServer() {}
func (UnimplementedTobaccoServiceServer) testEmbeddedByValue()                        {}

// UnsafeTobaccoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TobaccoServiceServer will
// result in compilation errors.
type UnsafeTobaccoServiceServer interface {
	mustEmbedUnimplementedTobaccoServiceServer()
}

func RegisterTobaccoServiceServer(s grpc.ServiceRegistrar, srv TobaccoServiceServer) {
	// If the following call panics, it indicates UnimplementedTobaccoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TobaccoService_ServiceDesc, srv)
}

func _TobaccoService_CreateTobacco_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTobaccoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TobaccoServiceServer).CreateTobacco(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TobaccoService_CreateTobacco_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TobaccoServiceServer).CreateTobacco(ctx, req.(*CreateTobaccoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TobaccoService_GetTobacco_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTobaccoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TobaccoServiceServer).GetTobacco(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TobaccoService_GetTobacco_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TobaccoServiceServer).GetTobacco(ctx, req.(*GetTobaccoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TobaccoService_ListTobaccos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTobaccosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TobaccoServiceServer).ListTobaccos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TobaccoService_ListTobaccos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TobaccoServiceServer).ListTobaccos(ctx, req.(*ListTobaccosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TobaccoService_ServiceDesc is the grpc.ServiceDesc for TobaccoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TobaccoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "likewhat.TobaccoService",
	HandlerType: (*TobaccoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTobacco",
			Handler:    _TobaccoService_CreateTobacco_Handler,
		},
		{
			MethodName: "GetTobacco",
			Handler:    _TobaccoService_GetTobacco_Handler,
		},
		{
			MethodName: "ListTobaccos",
			Handler:    _TobaccoService_ListTobaccos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/like_what/like_what.proto",
}

const (
	ManufactureService_CreateManufacture_FullMethodName = "/likewhat.ManufactureService/CreateManufacture"
	ManufactureService_ListManufactures_FullMethodName  = "/likewhat.ManufactureService/ListManufactures"
	ManufactureService_EditManufacture_FullMethodName   = "/likewhat.ManufactureService/EditManufacture"
	ManufactureService_DeleteManufacture_FullMethodName = "/likewhat.ManufactureService/DeleteManufacture"
)

// ManufactureServiceClient is the client API for ManufactureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManufactureServiceClient interface {
	CreateManufacture(ctx context.Context, in *CreateManufactureRequest, opts ...grpc.CallOption) (*Manufacture, error)
	ListManufactures(ctx context.Context, in *ListManufactureRequest, opts ...grpc.CallOption) (*ListManufactureRespone, error)
	EditManufacture(ctx context.Context, in *EditManufactureRequest, opts ...grpc.CallOption) (*Manufacture, error)
	DeleteManufacture(ctx context.Context, in *DeleteManufactureRequest, opts ...grpc.CallOption) (*DeleteManufactureResponse, error)
}

type manufactureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManufactureServiceClient(cc grpc.ClientConnInterface) ManufactureServiceClient {
	return &manufactureServiceClient{cc}
}

func (c *manufactureServiceClient) CreateManufacture(ctx context.Context, in *CreateManufactureRequest, opts ...grpc.CallOption) (*Manufacture, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manufacture)
	err := c.cc.Invoke(ctx, ManufactureService_CreateManufacture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manufactureServiceClient) ListManufactures(ctx context.Context, in *ListManufactureRequest, opts ...grpc.CallOption) (*ListManufactureRespone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManufactureRespone)
	err := c.cc.Invoke(ctx, ManufactureService_ListManufactures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manufactureServiceClient) EditManufacture(ctx context.Context, in *EditManufactureRequest, opts ...grpc.CallOption) (*Manufacture, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manufacture)
	err := c.cc.Invoke(ctx, ManufactureService_EditManufacture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manufactureServiceClient) DeleteManufacture(ctx context.Context, in *DeleteManufactureRequest, opts ...grpc.CallOption) (*DeleteManufactureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteManufactureResponse)
	err := c.cc.Invoke(ctx, ManufactureService_DeleteManufacture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManufactureServiceServer is the server API for ManufactureService service.
// All implementations must embed UnimplementedManufactureServiceServer
// for forward compatibility.
type ManufactureServiceServer interface {
	CreateManufacture(context.Context, *CreateManufactureRequest) (*Manufacture, error)
	ListManufactures(context.Context, *ListManufactureRequest) (*ListManufactureRespone, error)
	EditManufacture(context.Context, *EditManufactureRequest) (*Manufacture, error)
	DeleteManufacture(context.Context, *DeleteManufactureRequest) (*DeleteManufactureResponse, error)
	mustEmbedUnimplementedManufactureServiceServer()
}

// UnimplementedManufactureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManufactureServiceServer struct{}

func (UnimplementedManufactureServiceServer) CreateManufacture(context.Context, *CreateManufactureRequest) (*Manufacture, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateManufacture not implemented")
}
func (UnimplementedManufactureServiceServer) ListManufactures(context.Context, *ListManufactureRequest) (*ListManufactureRespone, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManufactures not implemented")
}
func (UnimplementedManufactureServiceServer) EditManufacture(context.Context, *EditManufactureRequest) (*Manufacture, error) {
	return nil, status.Error(codes.Unimplemented, "method EditManufacture not implemented")
}
func (UnimplementedManufactureServiceServer) DeleteManufacture(context.Context, *DeleteManufactureRequest) (*DeleteManufactureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteManufacture not implemented")
}
func (UnimplementedManufactureServiceServer) mustEmbedUnimplementedManufactureServiceServer() {}
func (UnimplementedManufactureServiceServer) testEmbeddedByValue()                            {}

// UnsafeManufactureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManufactureServiceServer will
// result in compilation errors.
type UnsafeManufactureServiceServer interface {
	mustEmbedUnimplementedManufactureServiceServer()
}

func RegisterManufactureServiceServer(s grpc.ServiceRegistrar, srv ManufactureServiceServer) {
	// If the following call panics, it indicates UnimplementedManufactureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManufactureService_ServiceDesc, srv)
}

func _ManufactureService_CreateManufacture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManufactureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManufactureServiceServer).CreateManufacture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManufactureService_CreateManufacture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManufactureServiceServer).CreateManufacture(ctx, req.(*CreateManufactureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManufactureService_ListManufactures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManufactureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManufactureServiceServer).ListManufactures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManufactureService_ListManufactures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManufactureServiceServer).ListManufactures(ctx, req.(*ListManufactureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManufactureService_EditManufacture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditManufactureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManufactureServiceServer).EditManufacture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManufactureService_EditManufacture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManufactureServiceServer).EditManufacture(ctx, req.(*EditManufactureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManufactureService_DeleteManufacture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManufactureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManufactureServiceServer).DeleteManufacture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManufactureService_DeleteManufacture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManufactureServiceServer).DeleteManufacture(ctx, req.(*DeleteManufactureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManufactureService_ServiceDesc is the grpc.ServiceDesc for ManufactureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManufactureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "likewhat.ManufactureService",
	HandlerType: (*ManufactureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateManufacture",
			Handler:    _ManufactureService_CreateManufacture_Handler,
		},
		{
			MethodName: "ListManufactures",
			Handler:    _ManufactureService_ListManufactures_Handler,
		},
		{
			MethodName: "EditManufacture",
			Handler:    _ManufactureService_EditManufacture_Handler,
		},
		{
			MethodName: "DeleteManufacture",
			Handler:    _ManufactureService_DeleteManufacture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/like_what/like_what.proto",
}
