// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/like_what/like_what.proto

package likewhat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TobaccoService_CreateTobacco_FullMethodName = "/likewhat.TobaccoService/CreateTobacco"
	TobaccoService_GetTobacco_FullMethodName    = "/likewhat.TobaccoService/GetTobacco"
	TobaccoService_ListTobaccos_FullMethodName  = "/likewhat.TobaccoService/ListTobaccos"
)

// TobaccoServiceClient is the client API for TobaccoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TobaccoService manages a collection of product tobaccos.
type TobaccoServiceClient interface {
	CreateTobacco(ctx context.Context, in *CreateTobaccoRequest, opts ...grpc.CallOption) (*Tobacco, error)
	GetTobacco(ctx context.Context, in *GetTobaccoRequest, opts ...grpc.CallOption) (*Tobacco, error)
	ListTobaccos(ctx context.Context, in *ListTobaccosRequest, opts ...grpc.CallOption) (*ListTobaccosResponse, error)
}

type tobaccoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTobaccoServiceClient(cc grpc.ClientConnInterface) TobaccoServiceClient {
	return &tobaccoServiceClient{cc}
}

func (c *tobaccoServiceClient) CreateTobacco(ctx context.Context, in *CreateTobaccoRequest, opts ...grpc.CallOption) (*Tobacco, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tobacco)
	err := c.cc.Invoke(ctx, TobaccoService_CreateTobacco_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tobaccoServiceClient) GetTobacco(ctx context.Context, in *GetTobaccoRequest, opts ...grpc.CallOption) (*Tobacco, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tobacco)
	err := c.cc.Invoke(ctx, TobaccoService_GetTobacco_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tobaccoServiceClient) ListTobaccos(ctx context.Context, in *ListTobaccosRequest, opts ...grpc.CallOption) (*ListTobaccosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTobaccosResponse)
	err := c.cc.Invoke(ctx, TobaccoService_ListTobaccos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TobaccoServiceServer is the server API for TobaccoService service.
// All implementations must embed UnimplementedTobaccoServiceServer
// for forward compatibility.
//
// TobaccoService manages a collection of product tobaccos.
type TobaccoServiceServer interface {
	CreateTobacco(context.Context, *CreateTobaccoRequest) (*Tobacco, error)
	GetTobacco(context.Context, *GetTobaccoRequest) (*Tobacco, error)
	ListTobaccos(context.Context, *ListTobaccosRequest) (*ListTobaccosResponse, error)
	mustEmbedUnimplementedTobaccoServiceServer()
}

// UnimplementedTobaccoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTobaccoServiceServer struct{}

func (UnimplementedTobaccoServiceServer) CreateTobacco(context.Context, *CreateTobaccoRequest) (*Tobacco, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTobacco not implemented")
}
func (UnimplementedTobaccoServiceServer) GetTobacco(context.Context, *GetTobaccoRequest) (*Tobacco, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTobacco not implemented")
}
func (UnimplementedTobaccoServiceServer) ListTobaccos(context.Context, *ListTobaccosRequest) (*ListTobaccosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTobaccos not implemented")
}
func (UnimplementedTobaccoServiceServer) mustEmbedUnimplementedTobaccoServiceServer() {}
func (UnimplementedTobaccoServiceServer) testEmbeddedByValue()                        {}

// UnsafeTobaccoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TobaccoServiceServer will
// result in compilation errors.
type UnsafeTobaccoServiceServer interface {
	mustEmbedUnimplementedTobaccoServiceServer()
}

func RegisterTobaccoServiceServer(s grpc.ServiceRegistrar, srv TobaccoServiceServer) {
	// If the following call panics, it indicates UnimplementedTobaccoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TobaccoService_ServiceDesc, srv)
}

func _TobaccoService_CreateTobacco_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTobaccoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TobaccoServiceServer).CreateTobacco(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TobaccoService_CreateTobacco_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TobaccoServiceServer).CreateTobacco(ctx, req.(*CreateTobaccoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TobaccoService_GetTobacco_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTobaccoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TobaccoServiceServer).GetTobacco(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TobaccoService_GetTobacco_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TobaccoServiceServer).GetTobacco(ctx, req.(*GetTobaccoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TobaccoService_ListTobaccos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTobaccosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TobaccoServiceServer).ListTobaccos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TobaccoService_ListTobaccos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TobaccoServiceServer).ListTobaccos(ctx, req.(*ListTobaccosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TobaccoService_ServiceDesc is the grpc.ServiceDesc for TobaccoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TobaccoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "likewhat.TobaccoService",
	HandlerType: (*TobaccoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTobacco",
			Handler:    _TobaccoService_CreateTobacco_Handler,
		},
		{
			MethodName: "GetTobacco",
			Handler:    _TobaccoService_GetTobacco_Handler,
		},
		{
			MethodName: "ListTobaccos",
			Handler:    _TobaccoService_ListTobaccos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/like_what/like_what.proto",
}
