// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.0
// source: api/like_what/like_what.proto

package likewhat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tobacco struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Taste         string                 `protobuf:"bytes,2,opt,name=taste,proto3" json:"taste,omitempty"`
	Manufacture   *Manufacture           `protobuf:"bytes,4,opt,name=manufacture,proto3" json:"manufacture,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tobacco) Reset() {
	*x = Tobacco{}
	mi := &file_api_like_what_like_what_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tobacco) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tobacco) ProtoMessage() {}

func (x *Tobacco) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tobacco.ProtoReflect.Descriptor instead.
func (*Tobacco) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{0}
}

func (x *Tobacco) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tobacco) GetTaste() string {
	if x != nil {
		return x.Taste
	}
	return ""
}

func (x *Tobacco) GetManufacture() *Manufacture {
	if x != nil {
		return x.Manufacture
	}
	return nil
}

func (x *Tobacco) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tobacco) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Tobacco) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreateTobaccoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taste         string                 `protobuf:"bytes,1,opt,name=taste,proto3" json:"taste,omitempty"`
	Photo         string                 `protobuf:"bytes,2,opt,name=photo,proto3" json:"photo,omitempty"`
	ManufactureId string                 `protobuf:"bytes,3,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTobaccoRequest) Reset() {
	*x = CreateTobaccoRequest{}
	mi := &file_api_like_what_like_what_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTobaccoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTobaccoRequest) ProtoMessage() {}

func (x *CreateTobaccoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTobaccoRequest.ProtoReflect.Descriptor instead.
func (*CreateTobaccoRequest) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTobaccoRequest) GetTaste() string {
	if x != nil {
		return x.Taste
	}
	return ""
}

func (x *CreateTobaccoRequest) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *CreateTobaccoRequest) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

type GetTobaccoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTobaccoRequest) Reset() {
	*x = GetTobaccoRequest{}
	mi := &file_api_like_what_like_what_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTobaccoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTobaccoRequest) ProtoMessage() {}

func (x *GetTobaccoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTobaccoRequest.ProtoReflect.Descriptor instead.
func (*GetTobaccoRequest) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{2}
}

func (x *GetTobaccoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTobaccosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taste         string                 `protobuf:"bytes,1,opt,name=taste,proto3" json:"taste,omitempty"`
	ManufactureId []string               `protobuf:"bytes,2,rep,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTobaccosRequest) Reset() {
	*x = ListTobaccosRequest{}
	mi := &file_api_like_what_like_what_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTobaccosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTobaccosRequest) ProtoMessage() {}

func (x *ListTobaccosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTobaccosRequest.ProtoReflect.Descriptor instead.
func (*ListTobaccosRequest) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{3}
}

func (x *ListTobaccosRequest) GetTaste() string {
	if x != nil {
		return x.Taste
	}
	return ""
}

func (x *ListTobaccosRequest) GetManufactureId() []string {
	if x != nil {
		return x.ManufactureId
	}
	return nil
}

type ListTobaccosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tobaccos      []*Tobacco             `protobuf:"bytes,1,rep,name=tobaccos,proto3" json:"tobaccos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTobaccosResponse) Reset() {
	*x = ListTobaccosResponse{}
	mi := &file_api_like_what_like_what_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTobaccosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTobaccosResponse) ProtoMessage() {}

func (x *ListTobaccosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTobaccosResponse.ProtoReflect.Descriptor instead.
func (*ListTobaccosResponse) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{4}
}

func (x *ListTobaccosResponse) GetTobaccos() []*Tobacco {
	if x != nil {
		return x.Tobaccos
	}
	return nil
}

type CreateManufactureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManufactureRequest) Reset() {
	*x = CreateManufactureRequest{}
	mi := &file_api_like_what_like_what_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManufactureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManufactureRequest) ProtoMessage() {}

func (x *CreateManufactureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManufactureRequest.ProtoReflect.Descriptor instead.
func (*CreateManufactureRequest) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{5}
}

func (x *CreateManufactureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Manufacture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacture) Reset() {
	*x = Manufacture{}
	mi := &file_api_like_what_like_what_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacture) ProtoMessage() {}

func (x *Manufacture) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacture.ProtoReflect.Descriptor instead.
func (*Manufacture) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{6}
}

func (x *Manufacture) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manufacture) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacture) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Manufacture) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Manufacture) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ListManufacturesRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Filter        *ListManufacturesRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PerPage       uint64                          `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Page          uint64                          `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturesRequest) Reset() {
	*x = ListManufacturesRequest{}
	mi := &file_api_like_what_like_what_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturesRequest) ProtoMessage() {}

func (x *ListManufacturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturesRequest.ProtoReflect.Descriptor instead.
func (*ListManufacturesRequest) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{7}
}

func (x *ListManufacturesRequest) GetFilter() *ListManufacturesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListManufacturesRequest) GetPerPage() uint64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListManufacturesRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListManufacturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufactures  []*Manufacture         `protobuf:"bytes,1,rep,name=manufactures,proto3" json:"manufactures,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPage      bool                   `protobuf:"varint,3,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturesResponse) Reset() {
	*x = ListManufacturesResponse{}
	mi := &file_api_like_what_like_what_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturesResponse) ProtoMessage() {}

func (x *ListManufacturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturesResponse.ProtoReflect.Descriptor instead.
func (*ListManufacturesResponse) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{8}
}

func (x *ListManufacturesResponse) GetManufactures() []*Manufacture {
	if x != nil {
		return x.Manufactures
	}
	return nil
}

func (x *ListManufacturesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListManufacturesResponse) GetNextPage() bool {
	if x != nil {
		return x.NextPage
	}
	return false
}

type EditManufactureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditManufactureRequest) Reset() {
	*x = EditManufactureRequest{}
	mi := &file_api_like_what_like_what_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditManufactureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditManufactureRequest) ProtoMessage() {}

func (x *EditManufactureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditManufactureRequest.ProtoReflect.Descriptor instead.
func (*EditManufactureRequest) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{9}
}

func (x *EditManufactureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditManufactureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteManufactureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManufactureRequest) Reset() {
	*x = DeleteManufactureRequest{}
	mi := &file_api_like_what_like_what_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManufactureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManufactureRequest) ProtoMessage() {}

func (x *DeleteManufactureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManufactureRequest.ProtoReflect.Descriptor instead.
func (*DeleteManufactureRequest) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteManufactureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteManufactureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDeleted     bool                   `protobuf:"varint,1,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManufactureResponse) Reset() {
	*x = DeleteManufactureResponse{}
	mi := &file_api_like_what_like_what_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManufactureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManufactureResponse) ProtoMessage() {}

func (x *DeleteManufactureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManufactureResponse.ProtoReflect.Descriptor instead.
func (*DeleteManufactureResponse) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteManufactureResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *DeleteManufactureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListManufacturesRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Наименование производителя поиск.
	NameLike string `protobuf:"bytes,1,opt,name=name_like,json=nameLike,proto3" json:"name_like,omitempty"`
	// Поиск по идентификаторам.
	IdsIn         []string `protobuf:"bytes,2,rep,name=ids_in,json=idsIn,proto3" json:"ids_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturesRequest_Filter) Reset() {
	*x = ListManufacturesRequest_Filter{}
	mi := &file_api_like_what_like_what_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturesRequest_Filter) ProtoMessage() {}

func (x *ListManufacturesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_what_like_what_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturesRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListManufacturesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_like_what_like_what_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListManufacturesRequest_Filter) GetNameLike() string {
	if x != nil {
		return x.NameLike
	}
	return ""
}

func (x *ListManufacturesRequest_Filter) GetIdsIn() []string {
	if x != nil {
		return x.IdsIn
	}
	return nil
}

var File_api_like_what_like_what_proto protoreflect.FileDescriptor

const file_api_like_what_like_what_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/like_what/like_what.proto\x12\blikewhat\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x02\n" +
	"\aTobacco\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05taste\x18\x02 \x01(\tR\x05taste\x127\n" +
	"\vmanufacture\x18\x04 \x01(\v2\x15.likewhat.ManufactureR\vmanufacture\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"i\n" +
	"\x14CreateTobaccoRequest\x12\x14\n" +
	"\x05taste\x18\x01 \x01(\tR\x05taste\x12\x14\n" +
	"\x05photo\x18\x02 \x01(\tR\x05photo\x12%\n" +
	"\x0emanufacture_id\x18\x03 \x01(\tR\rmanufactureId\"#\n" +
	"\x11GetTobaccoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x13ListTobaccosRequest\x12\x14\n" +
	"\x05taste\x18\x01 \x01(\tR\x05taste\x12%\n" +
	"\x0emanufacture_id\x18\x02 \x03(\tR\rmanufactureId\"E\n" +
	"\x14ListTobaccosResponse\x12-\n" +
	"\btobaccos\x18\x01 \x03(\v2\x11.likewhat.TobaccoR\btobaccos\".\n" +
	"\x18CreateManufactureRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xe2\x01\n" +
	"\vManufacture\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xc8\x01\n" +
	"\x17ListManufacturesRequest\x12@\n" +
	"\x06filter\x18\x01 \x01(\v2(.likewhat.ListManufacturesRequest.FilterR\x06filter\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x04R\aperPage\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x1a<\n" +
	"\x06Filter\x12\x1b\n" +
	"\tname_like\x18\x01 \x01(\tR\bnameLike\x12\x15\n" +
	"\x06ids_in\x18\x02 \x03(\tR\x05idsIn\"\x93\x01\n" +
	"\x18ListManufacturesResponse\x129\n" +
	"\fmanufactures\x18\x01 \x03(\v2\x15.likewhat.ManufactureR\fmanufactures\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x1b\n" +
	"\tnext_page\x18\x03 \x01(\bR\bnextPage\"<\n" +
	"\x16EditManufactureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x18DeleteManufactureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x19DeleteManufactureResponse\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x01 \x01(\bR\tisDeleted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe1\x01\n" +
	"\x0eTobaccoService\x12B\n" +
	"\rCreateTobacco\x12\x1e.likewhat.CreateTobaccoRequest\x1a\x11.likewhat.Tobacco\x12<\n" +
	"\n" +
	"GetTobacco\x12\x1b.likewhat.GetTobaccoRequest\x1a\x11.likewhat.Tobacco\x12M\n" +
	"\fListTobaccos\x12\x1d.likewhat.ListTobaccosRequest\x1a\x1e.likewhat.ListTobaccosResponse2\xe9\x02\n" +
	"\x12ManufactureService\x12N\n" +
	"\x11CreateManufacture\x12\".likewhat.CreateManufactureRequest\x1a\x15.likewhat.Manufacture\x12Y\n" +
	"\x10ListManufactures\x12!.likewhat.ListManufacturesRequest\x1a\".likewhat.ListManufacturesResponse\x12J\n" +
	"\x0fEditManufacture\x12 .likewhat.EditManufactureRequest\x1a\x15.likewhat.Manufacture\x12\\\n" +
	"\x11DeleteManufacture\x12\".likewhat.DeleteManufactureRequest\x1a#.likewhat.DeleteManufactureResponseB9Z7github.com/Parnishkaspb/LikeWhat/pkg/like_what;likewhatb\x06proto3"

var (
	file_api_like_what_like_what_proto_rawDescOnce sync.Once
	file_api_like_what_like_what_proto_rawDescData []byte
)

func file_api_like_what_like_what_proto_rawDescGZIP() []byte {
	file_api_like_what_like_what_proto_rawDescOnce.Do(func() {
		file_api_like_what_like_what_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_like_what_like_what_proto_rawDesc), len(file_api_like_what_like_what_proto_rawDesc)))
	})
	return file_api_like_what_like_what_proto_rawDescData
}

var file_api_like_what_like_what_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_like_what_like_what_proto_goTypes = []any{
	(*Tobacco)(nil),                        // 0: likewhat.Tobacco
	(*CreateTobaccoRequest)(nil),           // 1: likewhat.CreateTobaccoRequest
	(*GetTobaccoRequest)(nil),              // 2: likewhat.GetTobaccoRequest
	(*ListTobaccosRequest)(nil),            // 3: likewhat.ListTobaccosRequest
	(*ListTobaccosResponse)(nil),           // 4: likewhat.ListTobaccosResponse
	(*CreateManufactureRequest)(nil),       // 5: likewhat.CreateManufactureRequest
	(*Manufacture)(nil),                    // 6: likewhat.Manufacture
	(*ListManufacturesRequest)(nil),        // 7: likewhat.ListManufacturesRequest
	(*ListManufacturesResponse)(nil),       // 8: likewhat.ListManufacturesResponse
	(*EditManufactureRequest)(nil),         // 9: likewhat.EditManufactureRequest
	(*DeleteManufactureRequest)(nil),       // 10: likewhat.DeleteManufactureRequest
	(*DeleteManufactureResponse)(nil),      // 11: likewhat.DeleteManufactureResponse
	(*ListManufacturesRequest_Filter)(nil), // 12: likewhat.ListManufacturesRequest.Filter
	(*timestamppb.Timestamp)(nil),          // 13: google.protobuf.Timestamp
}
var file_api_like_what_like_what_proto_depIdxs = []int32{
	6,  // 0: likewhat.Tobacco.manufacture:type_name -> likewhat.Manufacture
	13, // 1: likewhat.Tobacco.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: likewhat.Tobacco.updated_at:type_name -> google.protobuf.Timestamp
	13, // 3: likewhat.Tobacco.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 4: likewhat.ListTobaccosResponse.tobaccos:type_name -> likewhat.Tobacco
	13, // 5: likewhat.Manufacture.created_at:type_name -> google.protobuf.Timestamp
	13, // 6: likewhat.Manufacture.updated_at:type_name -> google.protobuf.Timestamp
	13, // 7: likewhat.Manufacture.deleted_at:type_name -> google.protobuf.Timestamp
	12, // 8: likewhat.ListManufacturesRequest.filter:type_name -> likewhat.ListManufacturesRequest.Filter
	6,  // 9: likewhat.ListManufacturesResponse.manufactures:type_name -> likewhat.Manufacture
	1,  // 10: likewhat.TobaccoService.CreateTobacco:input_type -> likewhat.CreateTobaccoRequest
	2,  // 11: likewhat.TobaccoService.GetTobacco:input_type -> likewhat.GetTobaccoRequest
	3,  // 12: likewhat.TobaccoService.ListTobaccos:input_type -> likewhat.ListTobaccosRequest
	5,  // 13: likewhat.ManufactureService.CreateManufacture:input_type -> likewhat.CreateManufactureRequest
	7,  // 14: likewhat.ManufactureService.ListManufactures:input_type -> likewhat.ListManufacturesRequest
	9,  // 15: likewhat.ManufactureService.EditManufacture:input_type -> likewhat.EditManufactureRequest
	10, // 16: likewhat.ManufactureService.DeleteManufacture:input_type -> likewhat.DeleteManufactureRequest
	0,  // 17: likewhat.TobaccoService.CreateTobacco:output_type -> likewhat.Tobacco
	0,  // 18: likewhat.TobaccoService.GetTobacco:output_type -> likewhat.Tobacco
	4,  // 19: likewhat.TobaccoService.ListTobaccos:output_type -> likewhat.ListTobaccosResponse
	6,  // 20: likewhat.ManufactureService.CreateManufacture:output_type -> likewhat.Manufacture
	8,  // 21: likewhat.ManufactureService.ListManufactures:output_type -> likewhat.ListManufacturesResponse
	6,  // 22: likewhat.ManufactureService.EditManufacture:output_type -> likewhat.Manufacture
	11, // 23: likewhat.ManufactureService.DeleteManufacture:output_type -> likewhat.DeleteManufactureResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_like_what_like_what_proto_init() }
func file_api_like_what_like_what_proto_init() {
	if File_api_like_what_like_what_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_like_what_like_what_proto_rawDesc), len(file_api_like_what_like_what_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_like_what_like_what_proto_goTypes,
		DependencyIndexes: file_api_like_what_like_what_proto_depIdxs,
		MessageInfos:      file_api_like_what_like_what_proto_msgTypes,
	}.Build()
	File_api_like_what_like_what_proto = out.File
	file_api_like_what_like_what_proto_goTypes = nil
	file_api_like_what_like_what_proto_depIdxs = nil
}
